name: my_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.6
  shared_preferences: ^2.3.5

  image_picker: ^1.2.1
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  sqflite: ^2.4.2
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/all assets/
